services:
  app:
    command: [ "fastapi", "run", "--host", "0.0.0.0", "src/main.py" ]
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=randomsecret12345678901234567890
      - DB_CONNECTION_STRING=sqlite:////app/data/dev.sqlite
    volumes:
      - sqlite_data:/app/data
    ports:
      - "8000:8000"

volumes:
  sqlite_data:
